package codewars.kyu4.stripcomments;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class StripCommentsTest {
    
    @Test
    public void stripComments() throws Exception {
        assertEquals(
                "apples, pears\ngrapes\nbananas",
                StripComments.stripComments( "apples, pears # and bananas\ngrapes\nbananas !apples", new String[] { "#", "!" } )
        );

        assertEquals(
                "a\nc\nd",
                StripComments.stripComments( "a #b\nc\nd $e f g", new String[] { "#", "$" } )
        );
    
        assertEquals(
                "\n" +
                        "\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "ecde\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "cf\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ef\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "ec\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "ff\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "be\n" +
                        "\n" +
                        "c\n" +
                        "b\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "db\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "caea\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "\n" +
                        "ec\n" +
                        "\n" +
                        "cc\n" +
                        "\n" +
                        "dba\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "fcc\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "ea\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "aff\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "aa\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "da\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "bf\n" +
                        "\n" +
                        "adc\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "]\n" +
                        "\n" +
                        "ecf\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "\n" +
                        "b",
                StripComments.stripComments( "\n" +
                        "\n" +
                        "!eabca\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "ecde\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "b!\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "cf\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "!\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "b!\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ef\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "ec\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "ff\n" +
                        "\n" +
                        "b!\n" +
                        "\n" +
                        "!\n" +
                        "\n" +
                        "\n" +
                        "be!\n" +
                        "\n" +
                        "c\n" +
                        "b\n" +
                        "\n" +
                        "!e\n" +
                        "\n" +
                        "db\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "!d!e\n" +
                        "\n" +
                        "caea\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "\n" +
                        "ec\n" +
                        "\n" +
                        "cc\n" +
                        "\n" +
                        "dba\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "fcc\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "!f\n" +
                        "\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "ea\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "aff\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "aa\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "!\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "da\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "!\n" +
                        "\n" +
                        "bf!ba\n" +
                        "\n" +
                        "adc\n" +
                        "\n" +
                        "a!\n" +
                        "\n" +
                        "!\n" +
                        "\n" +
                        "ecf\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "\n" +
                        "b", new String[] { "#", "$", "!", "-" } )
        );
    }
    
}

